export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/index/index',
    'pages/cart/index',
    'pages/profile/index',
    'pages/product/index',
    'pages/order-confirm/index',
    'pages/orders/index',
    'pages/logistics/index',
    'pages/invite/index',
    'pages/admin/index',
    'pages/jobs/index',
    'pages/affairs/index',
    'pages/barter/index',
    'pages/help-store/index',
    'pages/achievement/index',
    'pages/contribution/index',
    'pages/feature/index',
    'pages/contrib-mall/index',
    'pages/council/index',
    'pages/gov/index',
    'pages/health/index',
    'pages/groupon/index',
    'pages/volunteer/index',
    'pages/elder/index',
    'pages/messages/index',
    'pages/agri-rental/index',
    'pages/presale/index',
    'pages/pay/index',
    'pages/express/index',
    'pages/sales/index',
    'pages/exchange/index',
    'pages/agri-tech/index',
    'pages/property/index',
    'pages/finance/index',
    'pages/tourism/index',
    'pages/care/index',
    'pages/legal/index',
    'pages/school/index',
    'pages/heritage/index',
    'pages/civility/index',
    'pages/safety/index',
    'pages/org-code/index',
    'pages/neighbor/index',
    'pages/assistant/index',
    'pages/privacy/index',
    'pages/approval/index',
    'pages/family/index',
    'pages/service-center/index',
  ],
  // 供享·小卖部含 90 张商品图，独立分包，避免主包超 2MB 限制
  subPackages: [
    { root: 'pkgShop', pages: ['my-store/index'] },
    { root: 'pkgAdmin', pages: ['roster-import/index', 'village-config/index'] },
    { root: 'pkgParty', pages: ['party/index', 'party-help/index', 'party-wish/index', 'party-dues/index', 'party-map/index', 'village-party/index'] },
    { root: 'pkgPlatform', pages: ['platform/index', 'community/index', 'charity-auth/index', 'promotion/index', 'web3/index', 'settlement/index', 'my-assets/index', 'ai-store/index', 'prosperity/index', 'interest-community/index', 'breakeven/index', 'lifecycle/index', 'credit/index', 'digital-asset/index'] },
    { root: 'pkgLife', pages: ['spotlight/index', 'social/index', 'life/index', 'food/index', 'chess/index', 'travel/index', 'repair/index', 'activity/index', 'senior/index', 'errand/index', 'contrib-audit/index', 'contrib-submit/index', 'charity/index'] },
    { root: 'pkgDigital', pages: ['digital-village/index'] },
  ],
  // 位置接口声明：chooseLocation 搜全国地名 / openLocation 导航需要
  requiredPrivateInfos: ['chooseLocation', 'getLocation'],
  permission: {
    'scope.userLocation': { desc: '用于党建联建地图搜索地名、定位与导航' },
  },
  // 不使用微信原生 tabBar：底部导航需按角色（村委书记 / 村民）显示不同入口，
  // 原生 tabBar 是全局静态、最多 5 个且无法按角色切换，故改用自定义底部栏
  // （src/components/TabBar），各页面通过 reLaunch 切换。
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#16a34a',
    navigationBarTitleText: '供享村社',
    navigationBarTextStyle: 'white',
  },
});
